# Routes

# _home:
#     path:   ''
#     controller:   'HelloController'
#     action: 'run'
#     method: 'GET'

_home:
    path:   ''
    controller:   'UserController'
    action: 'home'
    method: 'GET'

_config:
    path: 'config'
    controller: 'ConfigController'
    action: 'config'