# Routes

home:
    path:   ''
    controller:   'UserController'
    action: 'home'
    method: 'GET'

_config:
    path: 'config'
    controller: 'ConfigController'
    action: 'config'

postProject:
	path: form/project
	controller: ProjectController
	action: postProject
	method: POST
