postTask:
    path: tasks/create/:project_id
    controller: TaskController
    action: postTask
    filters:
        require:
            project_id: '[\d-]+'

archiveTask:
    path: tasks/archive/:project_id/:id
    controller: TaskController
    action: archiveTask
    filters:
        require:
            project_id: '[\d-]+'
            id: '[\d-]+'

deleteTask:
    path: tasks/delete/:project_id/:id
    controller: TaskController
    action: deleteTask
    filters:
        require:
            project_id: '[\d-]+'
            id: '[\d-]+'

editTask:
    path: tasks/edit/:project_id/:id
    controller: TaskController
    action: editTask
    filters:
        require:
            project_id: '[\d-]+'
            id: '[\d-]+'

putTask:
    path: tasks/update/:project_id/:id
    controller: TaskController
    action: putTask
    filters:
        require:
            project_id: '[\d-]+'
            id: '[\d-]+'
