form_project:
    form:
        method: POST
        action: /form/project
        submit: 'Cr&eacute;er'
        structure: list
    fields:
        name:
            class: name
            type: text
            required: true
            label: Nom
            empty: false
        description:
            class: description
            type: textarea
