form_project:
    form:
        method: POST
        action: /form/project
        submit: 'Cr&eacute;er'
        structure: list
    fields:
        title:
            class: title
            type: text
            required: true
            label: Titre
            empty: false
        description:
            class: description
            type: textarea
